//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vacation_Req
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeTB()
        {
            this.RequestsTBs = new HashSet<RequestsTB>();
        }
    
        public long Emp_ID { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Title { get; set; }
        public int Dep_ID { get; set; }
    
        public virtual DepartmentTB DepartmentTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestsTB> RequestsTBs { get; set; }
    }
}
