//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vacation_Req
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_allData
    {
        public int Dep_ID { get; set; }
        public string Dep_Name { get; set; }
        public long Emp_ID { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Title { get; set; }
        public int Expr1 { get; set; }
        public long Req_ID { get; set; }
        public long Expr2 { get; set; }
        public System.DateTime Date_From { get; set; }
        public System.DateTime Date_To { get; set; }
        public System.DateTime Returning_Date { get; set; }
        public Nullable<System.DateTime> DateOfSub { get; set; }
        public string Notes { get; set; }
        public Nullable<int> TotalDays { get; set; }
    }
}
